import "bootstrap/dist/css/bootstrap.css";
import "react-toastify/dist/ReactToastify.css";
import "react-toastify";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "react-image-crop/dist/ReactCrop.css";
import { GlobalContextProvider } from "../context/Store";
import BootstrapClient from "../components/BootstrapClient";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import AppLink from "../components/AppLink";
import localFont from "next/font/local";
import { Bounce, ToastContainer } from "react-toastify";
const dejaVuBold = localFont({
  src: [
    {
      path: "../../public/assets/fonts/DejaVuSerifCondensed-Bold.ttf",
    },
  ],
  variable: "--font-dejaVuBold",
});
const dejaVuCondensed = localFont({
  src: [
    {
      path: "../../public/assets/fonts/DejaVuSerifCondensed.ttf",
    },
  ],
  variable: "--font-dejaVuCondensed",
});

const timesNewRoman = localFont({
  src: [
    {
      path: "../../public/assets/fonts/times.ttf",
    },
  ],
  variable: "--font-timesNewRoman",
});
const kalpurush = localFont({
  src: [
    {
      path: "../../public/assets/fonts/kalpurush.ttf",
    },
  ],
  variable: "--font-kalpurush",
});
const algerian = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Algerian.ttf",
    },
  ],
  variable: "--font-algerian",
});

export const metadata = {
  title: "WBTPTA AMTA WEST",
  description:
    "Welcome To WBTPTA Amta West Circle's Website. Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`container-fluid text-center ${kalpurush.variable} ${timesNewRoman.variable} ${dejaVuBold.variable} ${dejaVuCondensed.variable} ${algerian.variable}`}
        suppressHydrationWarning={true}
      >
        <AppLink />
        <GlobalContextProvider>
          <Navbar />
          <div className="my-3">{children}</div>
          <Footer />
          <ToastContainer
            position="top-right"
            autoClose={1500}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss={false}
            draggable
            pauseOnHover={false}
            theme="light"
            transition={Bounce}
          />
          <BootstrapClient />
        </GlobalContextProvider>
      </body>
    </html>
  );
}
